2019-05-02 21:26:49,545 ERROR: Exception on /quiz_grape_region/31/24 [GET] [in e:\programmes\python27\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "e:\programmes\python27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\programmes\python27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\programmes\python27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\programmes\python27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\programmes\python27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "e:\programmes\python27\lib\site-packages\flask_login\utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "E:\ARID6405\Documents\One drive\OneDrive\projets\wine_app\app\main\routes.py", line 381, in quiz_grape_region
    clean_vineyards = clean_vineyard(grape.vignobles)
  File "E:\ARID6405\Documents\One drive\OneDrive\projets\wine_app\app\main\routes.py", line 363, in clean_vineyard
    return vineyard.lower().replace('Ã´', 'o'). \
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
2019-05-02 21:32:08,859 INFO: Microblog startup [in E:\ARID6405\Documents\One drive\OneDrive\projets\wine_app\app\__init__.py:74]
2019-05-02 21:32:47,503 ERROR: Exception on /quiz_grape_region/31/24 [POST] [in e:\programmes\python27\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "e:\programmes\python27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\programmes\python27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\programmes\python27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\programmes\python27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\programmes\python27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "e:\programmes\python27\lib\site-packages\flask_login\utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "E:\ARID6405\Documents\One drive\OneDrive\projets\wine_app\app\main\routes.py", line 420, in quiz_grape_region
    clicked_is_positive = next(request.form.keys()).replace(u'.x', '')
TypeError: list object is not an iterator
2019-05-02 21:34:36,259 INFO: Microblog startup [in E:\ARID6405\Documents\One drive\OneDrive\projets\wine_app\app\__init__.py:74]
2019-05-02 21:34:49,342 ERROR: Exception on /quiz_grape_region/31/24 [POST] [in e:\programmes\python27\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "e:\programmes\python27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\programmes\python27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\programmes\python27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\programmes\python27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\programmes\python27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "e:\programmes\python27\lib\site-packages\flask_login\utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "E:\ARID6405\Documents\One drive\OneDrive\projets\wine_app\app\main\routes.py", line 420, in quiz_grape_region
    clicked_is_positive = next(request.form.keys()).replace('.x', '')
TypeError: list object is not an iterator
2019-05-02 21:37:33,167 ERROR: Exception on /quiz_aoc_region/33/123 [POST] [in e:\programmes\python27\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "e:\programmes\python27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\programmes\python27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\programmes\python27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\programmes\python27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\programmes\python27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "e:\programmes\python27\lib\site-packages\flask_login\utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "E:\ARID6405\Documents\One drive\OneDrive\projets\wine_app\app\main\routes.py", line 477, in quiz_aoc_region
    clicked_is_positive = next(request.form.keys()).replace(u'.x', '')
TypeError: list object is not an iterator
2019-05-02 22:22:46,546 INFO: Microblog startup [in E:\ARID6405\Documents\One drive\OneDrive\projets\wine_app\app\__init__.py:74]
2019-05-02 22:25:24,411 INFO: Microblog startup [in E:\ARID6405\Documents\One drive\OneDrive\projets\wine_app\app\__init__.py:74]
